
# Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
# Click nbfs://nbhost/SystemFileSystem/Templates/Other/Dockerfile to edit this template

FROM payara/server-full
copy target/BolsaTrabajoPRN335-1.0-SNAPSHOT.war

